sudo: false

language: ruby

rvm:
  - 2.3.8

env:
  global:
    - CC_TEST_REPORTER_ID=0a4c13b71635c00cee43aba776853ade9404cc745c42977e25a5877a3e148527

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - gem install bundler -v 2.0.2

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT